;allophone definitions    
#include "allophones.asm"

wordend     EQU ENDBIT|_PA5

; allophone data
ALLSTART
		DEFB	_ZZ,_YR,_OW,wordend
		DEFB	_WW,_AX,_AX,_NN1,wordend
		DEFB	_TT2,_UW2,wordend
		DEFB	_TH,_RR1,_IY,wordend
		DEFB	_FF,_FF,_OR,wordend
		DEFB	_FF,_FF,_AY,_VV,wordend
		DEFB	_SS,_SS,_IH,_IH,_PA3,_KK2,_SS,wordend
		DEFB	_SS,_SS,_EH,_EH,_VV,_IH,_NN1,wordend
		DEFB	_EY,_PA3,_TT2,wordend
		DEFB	_NN1,_AA,_AY,_NN1,wordend
		DEFB	_TT2,_EH,_EH,_NN1,wordend
		DEFB	_IH,_LL,_EH,_EH,_VV,_IH,_NN1,wordend
		DEFB	_TT2,_WH,_EH,_EH,_LL,_VV,wordend
		DEFB	_TH,_ER1,_PA2,_PA3,_TT2,_IY,_NN1,wordend
		DEFB	_FF,_OR,_PA2,_PA3,_TT2,_IY,_NN1,wordend
		DEFB	_FF,_IH,_FF,_PA2,_PA3,_TT2,_IY,_NN1,wordend
		DEFB	_SS,_SS,_IH,_PA3,_KK2,_SS,_PA2,_PA3,_TT2,_IY,_NN1,wordend
		DEFB	_SS,_SS,_EH,_VV,_EH,_NN1,_PA2,_PA3,_TT2,_IY,_NN1,wordend
		DEFB	_EY,_PA2,_PA3,_TT2,_IY,_NN1,wordend
		DEFB	_NN1,_AY,_NN1,_PA2,_PA3,_TT2,_IY,_NN1,wordend
		DEFB	_TT2,_WH,_EH,_EH,_NN1,_PA2,_PA3,_TT2,_IY,wordend
		DEFB	_TH,_ER2,_PA2,_PA3,_TH,_IY,wordend
		DEFB	_FF,_OR,_PA3,_TT2,_IY,wordend
		DEFB	_FF,_FF,_IH,_FF,_FF,_PA2,_PA3,_TT2,_IY,wordend
		DEFB	_SS,_SS,_IH,_PA3,_KK2,_SS,_PA2,_PA3,_TT2,_IY,wordend
		DEFB	_SS,_SS,_EH,_VV,_IH,_NN1,_PA2,_PA3,_TT2,_IY,wordend
		DEFB	_EY,_PA3,_TT2,_IY,wordend
		DEFB	_NN1,_AY,_NN1,_PA3,_TT2,_IY,wordend
		DEFB	_HH2,_AX,_AX,_NN1,_PA2,_DD2,_RR2,_IH,_IH,_PA1,_DD1,wordend
		DEFB	_TH,_AA,_AW,_ZZ,_TH,_PA1,_PA1,_NN1,_DD1,wordend
		DEFB	_MM,_IH,_IH,_LL,_YY1,_AX,_NN1,wordend
		DEFB	_SS,_SS,_AX,_AX,_NN1,_PA2,_DD2,_EY,wordend
		DEFB	_MM,_AX,_AX,_NN1,_PA2,_DD2,_EY,wordend
		DEFB	_TT2,_UW2,_ZZ,_PA2,_DD2,_EY,wordend
		DEFB	_WW,_EH,_EH,_NN1,_ZZ,_PA2,_DD2,_EY,wordend
		DEFB	_TH,_ER2,_ZZ,_PA2,_DD2,_EY,wordend
		DEFB	_FF,_RR2,_AY,_PA2,_DD2,_EY,wordend
		DEFB	_SS,_SS,_AE,_PA3,_TT2,_PA2,_DD2,_EY,wordend
		DEFB	_JH,_AE,_AE,_NN1,_YY2,_XR,_IY,wordend
		DEFB	_FF,_EH,_EH,_PA1,_BB1,_RR2,_UW2,_XR,_IY,wordend
		DEFB	_MM,_AR,_PA3,_CH,wordend
		DEFB	_EY,_PA3,_PP,_RR2,_IH,_IH,_LL,wordend
		DEFB	_MM,_EY,wordend
		DEFB	_JH,_UW2,_NN1,wordend
		DEFB	_JH,_UW1,_LL,_AY,wordend
		DEFB	_AO,_AO,_PA2,_GG2,_AX,_SS,_PA3,_TT1,wordend
		DEFB	_SS,_SS,_EH,_PA3,_PP,_PA3,_TT2,_EH,_EH,_MM,_PA1,_BB2,_ER1,wordend
		DEFB	_AA,_PA2,_KK2,_PA3,_TT2,_OW,_PA1,_BB2,_ER1,wordend
		DEFB	_NN2,_OW,_VV,_EH,_EH,_MM,_PA1,_BB2,_ER1,wordend
		DEFB	_DD2,_IY,_SS,_SS,_EH,_EH,_MM,_PA1,_BB2,_ER1,wordend
		DEFB	_EY,wordend
		DEFB	_BB2,_IY,wordend
		DEFB	_SS,_SS,_IY,wordend
		DEFB	_DD2,_IY,wordend
		DEFB	_IY,wordend
		DEFB	_EH,_EH,_FF,_FF,wordend
		DEFB	_JH,_IY,wordend
		DEFB	_EY,_PA2,_PA3,_CH,wordend
		DEFB	_AA,_AY,wordend
		DEFB	_JH,_EH,_EY,wordend
		DEFB	_KK1,_EH,_EY,wordend
		DEFB	_EH,_EH,_EL,wordend
		DEFB	_EH,_EH,_MM,wordend
		DEFB	_EH,_EH,_NN1,wordend
		DEFB	_OW,wordend
		DEFB	_PP,_IY,wordend
		DEFB	_KK1,_YY1,_UW2,wordend
		DEFB	_AR,wordend
		DEFB	_EH,_EH,_SS,_SS,wordend
		DEFB	_TT2,_IY,wordend
		DEFB	_YY1,_UW2,wordend
		DEFB	_VV,_IY,wordend
		DEFB	_DD2,_AX,_PA2,_BB2,_EL,_YY1,_UW2,wordend
		DEFB	_EH,_EH,_PA3,_KK2,_SS,_SS,wordend
		DEFB	_WW,_AY,wordend
		DEFB	_ZZ,_IY,wordend
		DEFB	_AX,_LL,_AR,_MM,wordend
		DEFB	_BB2,_EY,_DH2,wordend
		DEFB	_BB2,_EY,_DH2,_ER1,wordend
		DEFB	_BB2,_EY,_DH2,_IH,_NG,wordend
		DEFB	_BB2,_YR,wordend
		DEFB	_BB1,_RR2,_EH,_EH,_PA1,_DD1,wordend
		DEFB	_BB2,_AA,_AY,wordend
		DEFB	_KK1,_AE,_AE,_LL,_EH,_NN1,_PA2,_DD2,_ER1,wordend
		DEFB	_CH,_EH,_EH,_PA3,_KK2,wordend
		DEFB	_CH,_EH,_EH,_PA3,_KK2,_PA2,_TT2,wordend
		DEFB	_CH,_EH,_EH,_PA3,_KK1,_ER1,wordend
		DEFB	_CH,_EH,_EH,_PA3,_KK1,_ER1,_ZZ,wordend
		DEFB	_CH,_EH,_EH,_PA3,_KK1,_IH,_NG,wordend
		DEFB	_CH,_EH,_EH,_PA3,_KK1,_SS,wordend
		DEFB	_KK1,_LL,_AA,_AA,_PA3,_KK2,wordend
		DEFB	_KK1,_LL,_AW,_NN1,wordend
		DEFB	_KK3,_AA,_AA,_GG3,_NN1,_IH,_PA3,_TT2,_IH,_VV,wordend
		DEFB	_KK3,_AX,_LL,_AY,_DD1,wordend
		DEFB	_KK1,_AX,_MM,_PP,_YY1,_UW1,_TT2,_ER2,wordend
		DEFB	_KK3,_UH,_KK1,_IY,wordend
		DEFB	_KK3,_UW2,_PA3,_PP,wordend
		DEFB	_KK1,_ER2,_EH,_EH,_PA2,_KK2,_PA2,_TT1,wordend
		DEFB	_KK1,_ER2,_EH,_EH,_PA2,_KK2,_PA2,_TT2,_EH,_EH,_DD1,wordend
		DEFB	_KK1,_ER2,_EH,_EH,_PA2,_KK2,_PA2,_TT2,_IH,_NG,wordend
		DEFB	_KK1,_ER2,_EH,_EH,_PA2,_KK2,_PA2,_TT1,_SS,wordend
		DEFB	_KK1,_RR2,_AW,_NN1,wordend
		DEFB	_DD2,_EY,_PA3,_TT2,wordend
		DEFB	_DD2,_AO,_TT2,_ER1,wordend
		DEFB	_DD2,_EH,_EY,wordend
		DEFB	_DD2,_IH,_VV,_AY,_PA2,_DD2,_IH,_PA2,_DD1,wordend
		DEFB	_IY,_MM,_OW,_SH,_AX,_NN1,_AX,_EL,wordend
		DEFB	_EH,_EH,_PA1,_NN1,_GG1,_EY,_PA2,_JH,wordend
		DEFB	_EH,_EH,_PA1,_NN1,_GG1,_EY,_PA2,_JH,_MM,_EH,_EH,_NN1,_PA2,_PA3,_TT2,wordend
		DEFB	_EH,_EH,_PA1,_NN1,_GG1,_EY,_PA2,_JH,_IH,_ZZ,wordend
		DEFB	_EH,_EH,_PA1,_NN1,_GG1,_EY,_PA2,_JH,_IH,_NG,wordend
		DEFB	_EH,_NN1,_RR1,_EY,_PA2,_JH,wordend
		DEFB	_EH,_NN1,_RR1,_EY,_PA2,_JH,_PA2,_DD1,wordend
		DEFB	_EH,_NN1,_RR1,_EY,_PA2,_JH,_IH,_ZZ,wordend
		DEFB	_EH,_NN1,_RR1,_EY,_PA2,_JH,_IH,_NG,wordend
		DEFB	_IY,_PA2,_PA3,_KK3,_WH,_AX,_EL,wordend
		DEFB	_IY,_PA2,_PA3,_KK3,_WH,_AX,_EL,_ZZ,wordend
		DEFB	_EH,_XR,_OR,wordend
		DEFB	_EH,_SS,_SS,_PA3,_KK1,_EY,_PA3,_PP,wordend
		DEFB	_EH,_SS,_SS,_PA3,_KK1,_EY,_PA3,_PP,_PA2,_TT2,wordend
		DEFB	_EH,_SS,_SS,_PA3,_KK1,_EY,_PA3,_PP,_SS,wordend
		DEFB	_EH,_SS,_SS,_PA3,_KK1,_EY,_PA3,_PP,_IH,_NG,wordend
		DEFB	_EH,_KK1,_SS,_TT2,_EH,_EH,_NN1,_TT2,wordend
		DEFB	_FF,_ER2,wordend
		DEFB	_FF,_FF,_RR1,_IY,_ZZ,wordend
		DEFB	_FF,_FF,_RR1,_IY,_ZZ,_ER1,wordend
		DEFB	_FF,_FF,_RR1,_IY,_ZZ,_ER1,_ZZ,wordend
		DEFB	_FF,_FF,_RR1,_IY,_ZZ,_IH,_NG,wordend
		DEFB	_FF,_FF,_RR1,_OW,_ZZ,_EH,_NN1,wordend
		DEFB	_GG1,_EY,_PA2,_JH,wordend
		DEFB	_GG1,_EY,_PA2,_JH,_PA2,_DD1,wordend
		DEFB	_GG1,_EY,_PA2,_JH,_IH,_ZZ,wordend
		DEFB	_GG1,_EY,_PA2,_JH,_IH,_NG,wordend
		DEFB	_HH1,_EH,_LL,_OW,wordend
		DEFB	_AW,_ER1,wordend
		DEFB	_IH,_NN1,_FF,_FF,_IH,_IH,_NN1,_IH,_PA2,_PA3,_TT2,_IH,_VV,wordend
		DEFB	_IH,_NN1,_PA3,_TT2,_RR2,_IY,_PA1,_GG3,wordend
		DEFB	_IH,_NN1,_PA3,_TT2,_RR2,_IY,_PA1,_GG3,_PA2,_DD1,wordend
		DEFB	_IH,_NN1,_PA3,_TT2,_RR2,_IY,_PA1,_GG3,_ZZ,wordend
		DEFB	_IH,_NN1,_PA3,_TT2,_RR2,_IY,_PA1,_GG3,_IH,_NG,wordend
		DEFB	_IH,_IH,_NN1,_VV,_EH,_EH,_SS,_PA2,_PA3,_TT2,_IH,_PA1,_GG1,_EY,_PA2,_TT2,wordend
		DEFB	_IH,_IH,_NN1,_VV,_EH,_EH,_SS,_PA2,_PA3,_TT2,_IH,_PA1,_GG1,_EY,_PA2,_TT2,_IH,_PA2,_DD1,wordend
		DEFB	_IH,_IH,_NN1,_VV,_EH,_EH,_SS,_PA2,_PA3,_TT2,_IH,_PA1,_GG1,_EY,_PA2,_TT1,_SS,wordend
		DEFB	_IH,_IH,_NN1,_VV,_EH,_EH,_SS,_PA2,_PA3,_TT2,_IH,_PA1,_GG1,_EY,_PA2,_TT2,_IH,_NG,wordend
		DEFB	_IH,_IH,_NN1,_VV,_EH,_EH,_SS,_PA2,_PA3,_TT2,_IH,_PA1,_GG1,_EY,_PA2,_TT2,_ER1,wordend
		DEFB	_IH,_IH,_NN1,_VV,_EH,_EH,_SS,_PA2,_PA3,_TT2,_IH,_PA1,_GG1,_EY,_PA2,_TT2,_ER1,_ZZ,wordend
		DEFB	_KK1,_IY,wordend
		DEFB	_LL,_EH,_EH,_PA2,_JH,_JH,_SS,_SS,_LL,_EY,_PA2,_PA3,_TT2,wordend
		DEFB	_LL,_EH,_EH,_PA2,_JH,_JH,_SS,_SS,_LL,_EY,_PA2,_PA3,_TT2,_IH,_DD1,wordend
		DEFB	_LL,_EH,_EH,_PA2,_JH,_JH,_SS,_SS,_LL,_EY,_PA2,_PA3,_TT1,_SS,wordend
		DEFB	_LL,_EH,_EH,_PA2,_JH,_JH,_SS,_SS,_LL,_EY,_PA2,_PA3,_TT2,_IH,_NG,wordend
		DEFB	_LL,_EH,_EH,_PA2,_JH,_JH,_SS,_SS,_LL,_EY,_PA2,_PA3,_CH,_ER1,wordend
		DEFB	_LL,_EH,_EH,_PA3,_TT2,_ER1,wordend
		DEFB	_LL,_IH,_IH,_PA3,_TT2,_ER1,wordend
		DEFB	_LL,_IH,_IH,_PA3,_TT2,_EL,wordend
		DEFB	_MM,_EH,_EH,_MM,_ER2,_IY,_ZZ,wordend
		DEFB	_MM,_EH,_EH,_MM,_ER2,_IY,wordend
		DEFB	_MM,_IH,_NN1,_IH,_PA3,_TT2,wordend
		DEFB	_MM,_AX,_NN1,_TH,wordend
		DEFB	_NN1,_IH,_IH,_PA2,_PA3,_PP,wordend
		DEFB	_NN1,_IH,_IH,_PA2,_PA3,_PP,_PA3,_TT2,wordend
		DEFB	_NN1,_IH,_IH,_PA2,_PA3,_PP,_IH,_NG,wordend
		DEFB	_NN1,_IH,_IH,_PA2,_PA3,_PP,_SS,wordend
		DEFB	_NN2,_AX,_OW,wordend
		DEFB	_FF,_FF,_IH,_ZZ,_IH,_PA3,_KK1,_AX,_EL,wordend
		DEFB	_PP,_IH,_IH,_NN1,wordend
		DEFB	_PP,_IH,_IH,_NN1,_PA2,_DD1,wordend
		DEFB	_PP,_IH,_IH,_NN1,_IH,_NG,wordend
		DEFB	_PP,_IH,_IH,_NN1,_ZZ,wordend
		DEFB	_PP,_LL,_EH,_EH,_PA3,_JH,wordend
		DEFB	_PP,_LL,_EH,_EH,_PA3,_JH,_PA2,_DD1,wordend
		DEFB	_PP,_LL,_EH,_EH,_PA3,_JH,_IH,_ZZ,wordend
		DEFB	_PP,_LL,_EH,_EH,_PA3,_JH,_IH,_NG,wordend
		DEFB	_PP,_LL,_AX,_AX,_SS,_SS,wordend
		DEFB	_RR1,_EH,_EY,wordend
		DEFB	_RR1,_EH,_EY,_ZZ,wordend
		DEFB	_RR1,_EH,_EH,_PA1,_DD2,_IY,wordend
		DEFB	_RR1,_EH,_EH,_PA1,_DD1,wordend
		DEFB	_RR1,_OW,_PA2,_BB2,_AA,_PA3,_TT2,wordend
		DEFB	_RR1,_OW,_PA2,_BB2,_AA,_PA3,_TT1,_SS,wordend
		DEFB	_SS,_SS,_PA3,_KK3,_OR,wordend
		DEFB	_SS,_SS,_EH,_PA3,_KK1,_IH,_NN1,_PA2,_DD1,wordend
		DEFB	_SS,_SS,_EH,_EH,_NN1,_SS,_SS,_IH,_PA2,_PA3,_TT2,_IH,_VV,wordend
		DEFB	_SS,_SS,_EH,_EH,_NN1,_SS,_SS,_IH,_PA2,_PA3,_TT2,_IH,_VV,_IH,_PA2,_PA3,_TT2,_IY,wordend
		DEFB	_SS,_SS,_IH,_IH,_NN1,_SS,_SS,_YR,wordend
		DEFB	_SS,_SS,_IH,_IH,_NN1,_SS,_SS,_YR,_LL,_IY,wordend
		DEFB	_SS,_SS,_IH,_IH,_NN1,_SS,_SS,_EH,_EH,_RR1,_IH,_PA2,_PA3,_TT2,_IY,wordend
		DEFB	_SS,_SS,_IH,_IH,_SS,_PA3,_TT2,_ER1,wordend
		DEFB	_SS,_SS,_PA3,_PP,_IY,_PA3,_KK2,wordend
		DEFB	_SS,_SS,_PA3,_PP,_EH,_EH,_EL,wordend
		DEFB	_SS,_SS,_PA3,_PP,_EH,_EH,_EL,_PA3,_DD1,wordend
		DEFB	_SS,_SS,_PA3,_PP,_EH,_EH,_EL,_ER2,wordend
		DEFB	_SS,_SS,_PA3,_PP,_EH,_EH,_EL,_ER2,_ZZ,wordend
		DEFB	_SS,_SS,_PA3,_PP,_EH,_EH,_EL,_IH,_NG,wordend
		DEFB	_SS,_SS,_PA3,_PP,_EH,_EH,_EL,_ZZ,wordend
		DEFB	_SS,_SS,_PA3,_TT2,_AR,_PA3,_TT2,wordend
		DEFB	_SS,_SS,_PA3,_TT2,_AR,_PA3,_TT2,_IH,_PA1,_DD2,wordend
		DEFB	_SS,_SS,_PA3,_TT2,_AR,_PA3,_TT2,_ER1,wordend
		DEFB	_SS,_SS,_KK3,_TT2,_AR,_PA3,_TT2,_IH,_NG,wordend
		DEFB	_SS,_SS,_KK3,_TT2,_AR,_PA3,_TT1,_SS,wordend
		DEFB	_SS,_SS,_PA3,_TT1,_AA,_AA,_PA3,_PP,wordend
		DEFB	_SS,_SS,_PA3,_TT1,_AA,_AA,_PA3,_PP,_PA3,_TT2,wordend
		DEFB	_SS,_SS,_PA3,_TT1,_AA,_AA,_PA3,_PP,_ER1,wordend
		DEFB	_SS,_SS,_PA3,_TT1,_AA,_AA,_PA3,_PP,_IH,_NG,wordend
		DEFB	_SS,_SS,_PA3,_TT1,_AA,_AA,_PA3,_PP,_SS,wordend
		DEFB	_SS,_SS,_AX,_AX,_PA2,_BB1,_PA2,_JH,_EH,_PA3,_KK2,_PA3,_TT2,wordend
		DEFB	_SS,_SS,_AX,_PA2,_BB1,_PA2,_JH,_EH,_EH,_PA3,_KK2,_PA3,_TT2,wordend
		DEFB	_SS,_SS,_WW,_EH,_EH,_PA3,_TT2,wordend
		DEFB	_SS,_SS,_WW,_EH,_EH,_PA3,_TT2,_IH,_PA3,_DD1,wordend
		DEFB	_SS,_SS,_WW,_EH,_EH,_PA3,_TT2,_ER1,wordend
		DEFB	_SS,_SS,_WW,_EH,_EH,_PA3,_TT2,_ER1,_ZZ,wordend
		DEFB	_SS,_SS,_WW,_EH,_EH,_PA3,_TT2,_IH,_NG,wordend
		DEFB	_SS,_SS,_WW,_EH,_EH,_PA3,_TT2,_SS,wordend
		DEFB	_SS,_SS,_WH,_IH,_IH,_PA3,_CH,wordend
		DEFB	_SS,_SS,_WH,_IH,_IH,_PA3,_CH,_PA3,_TT2,wordend
		DEFB	_SS,_SS,_WH,_IH,_IH,_PA3,_CH,_IH,_ZZ,wordend
		DEFB	_SS,_SS,_WH,_IH,_IH,_PA3,_CH,_IH,_NG,wordend
		DEFB	_SS,_SS,_IH,_IH,_SS,_SS,_PA3,_TT2,_EH,_MM,wordend
		DEFB	_SS,_SS,_IH,_IH,_SS,_SS,_PA3,_TT2,_EH,_MM,_ZZ,wordend
		DEFB	_TT2,_AO,_AO,_PA2,_KK2,wordend
		DEFB	_TT2,_AO,_AO,_PA3,_KK2,_PA3,_TT2,wordend
		DEFB	_TT2,_AO,_AO,_PA3,_KK1,_ER1,wordend
		DEFB	_TT2,_AO,_AO,_PA3,_KK1,_ER1,_ZZ,wordend
		DEFB	_TT2,_AO,_AO,_PA3,_KK1,_IH,_NG,wordend
		DEFB	_TT2,_AO,_AO,_PA2,_KK2,_SS,wordend
		DEFB	_DH1,_EH,_EH,_NN1,wordend
		DEFB	_TH,_RR1,_EH,_EH,_PA2,_DD1,wordend
		DEFB	_TH,_RR1,_EH,_EH,_PA2,_DD2,_IH,_PA2,_DD1,wordend
		DEFB	_TH,_RR1,_EH,_EH,_PA2,_DD2,_ER1,wordend
		DEFB	_TH,_RR1,_EH,_EH,_PA2,_DD2,_ER1,_ZZ,wordend
		DEFB	_TH,_RR1,_EH,_EH,_PA2,_DD2,_IH,_NG,wordend
		DEFB	_TH,_RR1,_EH,_EH,_PA2,_DD2,_ZZ,wordend
		DEFB	_TT2,_AA,_AY,_MM,wordend
		DEFB	_TT2,_AA,_AY,_MM,_ZZ,wordend
		DEFB	_AX,_NG,_PA3,_KK3,_EL,wordend
		DEFB	_WW,_EY,_EL,wordend
		DEFB	_WW,_EY,_LL,_ER1,wordend
		DEFB	_WW,_EY,_LL,_ER1,_ZZ,wordend
		DEFB	_WW,_EY,_EL,_ZZ,wordend
		DEFB	_WW,_EY,_LL,_IH,_NG,wordend
		DEFB	_YY2,_YR,wordend
		DEFB	_YY2,_EH,_EH,_SS,_SS,wordend
