; word data
TXTSTART
		DEFB	_Z,_E,_R,_o
		DEFB	_O,_N,_e
		DEFB	_T,_W,_o
		DEFB	_T,_H,_R,_E,_e
		DEFB	_F,_O,_U,_r
		DEFB	_F,_I,_V,_e
		DEFB	_S,_I,_x
		DEFB	_S,_E,_V,_E,_n
		DEFB	_E,_I,_G,_H,_t
		DEFB	_N,_I,_N,_e
		DEFB	_T,_E,_n
		DEFB	_E,_L,_E,_V,_E,_n
		DEFB	_T,_W,_E,_L,_V,_e
		DEFB	_T,_H,_I,_R,_T,_E,_E,_n
		DEFB	_F,_O,_R,_T,_E,_E,_n
		DEFB	_F,_I,_F,_T,_E,_E,_n
		DEFB	_S,_I,_X,_T,_E,_E,_n
		DEFB	_S,_E,_V,_E,_N,_T,_E,_E,_n
		DEFB	_E,_I,_G,_H,_T,_E,_E,_n
		DEFB	_N,_I,_N,_E,_T,_E,_E,_n
		DEFB	_T,_W,_E,_N,_T,_y
		DEFB	_T,_H,_I,_R,_T,_y
		DEFB	_F,_O,_R,_T,_y
		DEFB	_F,_I,_F,_T,_y
		DEFB	_S,_I,_X,_T,_y
		DEFB	_S,_E,_V,_E,_N,_T,_y
		DEFB	_E,_I,_G,_H,_T,_y
		DEFB	_N,_I,_N,_E,_T,_y
		DEFB	_H,_U,_N,_D,_R,_E,_d
		DEFB	_T,_H,_O,_U,_S,_A,_N,_d
		DEFB	_M,_I,_L,_L,_I,_O,_n
		DEFB	_S,_U,_N,_D,_A,_y
		DEFB	_M,_O,_N,_D,_A,_y
		DEFB	_T,_U,_E,_S,_D,_A,_y
		DEFB	_W,_E,_D,_N,_E,_S,_D,_A,_y
		DEFB	_T,_H,_U,_R,_S,_D,_A,_y
		DEFB	_F,_R,_I,_D,_A,_y
		DEFB	_S,_A,_T,_U,_R,_D,_A,_y
		DEFB	_J,_A,_N,_U,_A,_R,_y
		DEFB	_F,_E,_B,_R,_U,_A,_R,_y
		DEFB	_M,_A,_R,_C,_h
		DEFB	_A,_P,_R,_I,_l
		DEFB	_M,_A,_y
		DEFB	_J,_U,_N,_e
		DEFB	_J,_U,_L,_y
		DEFB	_A,_U,_G,_U,_S,_t
		DEFB	_S,_E,_P,_T,_E,_M,_B,_E,_r
		DEFB	_O,_C,_T,_O,_B,_E,_r
		DEFB	_N,_O,_V,_E,_M,_B,_E,_r
		DEFB	_D,_E,_C,_E,_M,_B,_E,_r
		DEFB	_a
		DEFB	_b
		DEFB	_c
		DEFB	_d
		DEFB	_e
		DEFB	_f
		DEFB	_g
		DEFB	_h
		DEFB	_i
		DEFB	_j
		DEFB	_k
		DEFB	_l
		DEFB	_m
		DEFB	_n
		DEFB	_o
		DEFB	_p
		DEFB	_q
		DEFB	_r
		DEFB	_s
		DEFB	_t
		DEFB	_u
		DEFB	_v
		DEFB	_w
		DEFB	_x
		DEFB	_y
		DEFB	_z
		DEFB	_A,_L,_A,_R,_m
		DEFB	_B,_A,_T,_H,_e
		DEFB	_B,_A,_T,_H,_E,_r
		DEFB	_B,_A,_T,_H,_I,_N,_g
		DEFB	_B,_E,_E,_r
		DEFB	_B,_R,_E,_A,_d
		DEFB	_B,_y
		DEFB	_C,_A,_L,_E,_N,_D,_A,_r
		DEFB	_C,_H,_E,_C,_k
		DEFB	_C,_H,_E,_C,_K,_E,_d
		DEFB	_C,_H,_E,_C,_K,_E,_r
		DEFB	_C,_H,_E,_C,_K,_E,_R,_s
		DEFB	_C,_H,_E,_C,_K,_I,_N,_g
		DEFB	_C,_H,_E,_C,_K,_s
		DEFB	_C,_L,_O,_C,_k
		DEFB	_C,_L,_O,_W,_n
		DEFB	_C,_O,_G,_N,_I,_T,_I,_V,_e
		DEFB	_C,_O,_L,_L,_I,_D,_e
		DEFB	_C,_O,_M,_P,_U,_T,_E,_r
		DEFB	_C,_O,_O,_K,_I,_e
		DEFB	_C,_O,_O,_p
		DEFB	_C,_O,_R,_R,_E,_C,_t
		DEFB	_C,_O,_R,_R,_E,_C,_T,_E,_d
		DEFB	_C,_O,_R,_R,_E,_C,_T,_I,_N,_g
		DEFB	_C,_O,_R,_R,_E,_C,_T,_s
		DEFB	_C,_R,_O,_W,_n
		DEFB	_D,_A,_T,_e
		DEFB	_D,_A,_U,_G,_H,_T,_E,_r
		DEFB	_D,_A,_y
		DEFB	_D,_I,_V,_I,_D,_E,_d
		DEFB	_E,_M,_O,_T,_I,_O,_N,_A,_l
		DEFB	_E,_N,_G,_A,_G,_e
		DEFB	_E,_N,_G,_A,_G,_E,_M,_E,_N,_t
		DEFB	_E,_N,_G,_A,_G,_E,_s
		DEFB	_E,_N,_G,_A,_G,_I,_N,_g
		DEFB	_E,_N,_R,_A,_G,_e
		DEFB	_E,_N,_R,_A,_G,_E,_d
		DEFB	_E,_N,_R,_A,_G,_E,_s
		DEFB	_E,_N,_R,_A,_G,_I,_N,_g
		DEFB	_E,_Q,_U,_A,_l
		DEFB	_E,_Q,_U,_A,_L,_s
		DEFB	_E,_R,_R,_O,_r
		DEFB	_E,_S,_C,_A,_P,_e
		DEFB	_E,_S,_C,_A,_P,_E,_d
		DEFB	_E,_S,_C,_A,_P,_E,_s
		DEFB	_E,_S,_C,_A,_P,_I,_N,_g
		DEFB	_E,_X,_T,_E,_N,_t
		DEFB	_F,_I,_r
		DEFB	_F,_R,_E,_E,_Z,_e
		DEFB	_F,_R,_E,_E,_Z,_E,_r
		DEFB	_F,_R,_E,_E,_Z,_E,_R,_s
		DEFB	_F,_R,_E,_E,_Z,_I,_N,_g
		DEFB	_F,_R,_O,_Z,_E,_n
		DEFB	_G,_U,_A,_G,_e
		DEFB	_G,_U,_A,_G,_E,_d
		DEFB	_G,_U,_A,_G,_E,_s
		DEFB	_G,_U,_A,_G,_I,_N,_g
		DEFB	_H,_E,_L,_L,_o
		DEFB	_H,_O,_U,_r
		DEFB	_I,_N,_F,_I,_N,_I,_T,_I,_V,_e
		DEFB	_I,_N,_T,_R,_I,_G,_U,_e
		DEFB	_I,_N,_T,_R,_I,_G,_U,_E,_d
		DEFB	_I,_N,_T,_R,_I,_G,_U,_E,_s
		DEFB	_I,_N,_T,_R,_I,_G,_U,_I,_N,_g
		DEFB	_I,_N,_V,_E,_S,_T,_I,_G,_A,_T,_e
		DEFB	_I,_N,_V,_E,_S,_T,_I,_G,_A,_T,_E,_d
		DEFB	_I,_N,_V,_E,_S,_T,_I,_G,_A,_T,_E,_s
		DEFB	_I,_N,_V,_E,_S,_T,_I,_G,_A,_T,_I,_N,_g
		DEFB	_I,_N,_V,_E,_S,_T,_I,_G,_A,_T,_O,_r
		DEFB	_I,_N,_V,_E,_S,_T,_I,_G,_A,_T,_O,_R,_s
		DEFB	_K,_E,_y
		DEFB	_L,_E,_G,_I,_S,_L,_A,_T,_e
		DEFB	_L,_E,_G,_I,_S,_L,_A,_T,_E,_d
		DEFB	_L,_E,_G,_I,_S,_L,_A,_T,_E,_s
		DEFB	_L,_E,_G,_I,_S,_L,_A,_T,_I,_N,_g
		DEFB	_L,_E,_G,_I,_S,_L,_A,_T,_U,_R,_e
		DEFB	_L,_E,_T,_T,_E,_r
		DEFB	_L,_I,_T,_T,_E,_r
		DEFB	_L,_I,_T,_T,_L,_e
		DEFB	_M,_E,_M,_O,_R,_I,_E,_s
		DEFB	_M,_E,_M,_O,_R,_y
		DEFB	_M,_I,_N,_U,_T,_e
		DEFB	_M,_O,_N,_T,_h
		DEFB	_N,_I,_p
		DEFB	_N,_I,_P,_P,_E,_d
		DEFB	_N,_I,_P,_P,_I,_N,_g
		DEFB	_N,_I,_P,_s
		DEFB	_N,_o
		DEFB	_P,_H,_Y,_S,_I,_C,_A,_l
		DEFB	_P,_I,_n
		DEFB	_P,_I,_N,_N,_E,_d
		DEFB	_P,_I,_N,_N,_I,_N,_g
		DEFB	_P,_I,_N,_s
		DEFB	_P,_L,_E,_D,_G,_e
		DEFB	_P,_L,_E,_D,_G,_E,_d
		DEFB	_P,_L,_E,_D,_G,_E,_s
		DEFB	_P,_L,_E,_D,_G,_I,_N,_g
		DEFB	_P,_L,_U,_s
		DEFB	_R,_A,_y
		DEFB	_R,_A,_Y,_s
		DEFB	_R,_E,_A,_D,_y
		DEFB	_R,_E,_d
		DEFB	_R,_O,_B,_O,_t
		DEFB	_R,_O,_B,_O,_T,_s
		DEFB	_S,_C,_O,_R,_e
		DEFB	_S,_E,_C,_O,_N,_d
		DEFB	_S,_E,_N,_S,_I,_T,_I,_V,_e
		DEFB	_S,_E,_N,_S,_I,_T,_I,_V,_I,_T,_y
		DEFB	_S,_I,_N,_C,_E,_R,_e
		DEFB	_S,_I,_N,_C,_E,_R,_E,_L,_y
		DEFB	_S,_I,_N,_C,_E,_R,_I,_T,_y
		DEFB	_S,_I,_S,_T,_E,_r
		DEFB	_S,_P,_E,_A,_k
		DEFB	_S,_P,_E,_L,_l
		DEFB	_S,_P,_E,_L,_L,_E,_d
		DEFB	_S,_P,_E,_L,_L,_E,_r
		DEFB	_S,_P,_E,_L,_L,_E,_R,_s
		DEFB	_S,_P,_E,_L,_L,_I,_N,_g
		DEFB	_S,_P,_E,_L,_L,_s
		DEFB	_S,_T,_A,_R,_t
		DEFB	_S,_T,_A,_R,_T,_E,_d
		DEFB	_S,_T,_A,_R,_T,_E,_r
		DEFB	_S,_T,_A,_R,_T,_I,_N,_g
		DEFB	_S,_T,_A,_R,_T,_s
		DEFB	_S,_T,_O,_p
		DEFB	_S,_T,_O,_P,_P,_E,_d
		DEFB	_S,_T,_O,_P,_P,_E,_r
		DEFB	_S,_T,_O,_P,_P,_I,_N,_g
		DEFB	_S,_T,_O,_P,_s
		DEFB	_S,_U,_B,_J,_E,_C,_t
		DEFB	_S,_U,_B,_J,_E,_C,_t
		DEFB	_S,_W,_E,_A,_t
		DEFB	_S,_W,_E,_A,_T,_E,_d
		DEFB	_S,_W,_E,_A,_T,_E,_r
		DEFB	_S,_W,_E,_A,_T,_E,_R,_s
		DEFB	_S,_W,_E,_A,_T,_I,_N,_g
		DEFB	_S,_W,_E,_A,_T,_s
		DEFB	_S,_W,_I,_T,_C,_h
		DEFB	_S,_W,_I,_T,_C,_H,_E,_d
		DEFB	_S,_W,_I,_T,_C,_H,_E,_s
		DEFB	_S,_W,_I,_T,_C,_H,_I,_N,_g
		DEFB	_S,_Y,_S,_T,_E,_m
		DEFB	_S,_Y,_S,_T,_E,_M,_s
		DEFB	_T,_A,_L,_k
		DEFB	_T,_A,_L,_K,_E,_d
		DEFB	_T,_A,_L,_K,_E,_r
		DEFB	_T,_A,_L,_K,_E,_R,_s
		DEFB	_T,_A,_L,_K,_I,_N,_g
		DEFB	_T,_A,_L,_K,_s
		DEFB	_T,_H,_E,_n
		DEFB	_T,_H,_R,_E,_A,_d
		DEFB	_T,_H,_R,_E,_A,_D,_E,_d
		DEFB	_T,_H,_R,_E,_A,_D,_E,_r
		DEFB	_T,_H,_R,_E,_A,_D,_E,_R,_s
		DEFB	_T,_H,_R,_E,_A,_D,_I,_N,_g
		DEFB	_T,_H,_R,_E,_A,_D,_s
		DEFB	_T,_I,_M,_e
		DEFB	_T,_I,_M,_E,_s
		DEFB	_U,_N,_C,_L,_e
		DEFB	_W,_H,_A,_L,_e
		DEFB	_W,_H,_A,_L,_E,_r
		DEFB	_W,_H,_A,_L,_E,_R,_s
		DEFB	_W,_H,_A,_L,_E,_s
		DEFB	_W,_H,_A,_L,_I,_N,_g
		DEFB	_Y,_E,_A,_r
		DEFB	_Y,_E,_s

